DROP SEQUENCE  SEQ_FUNCIONARIO;
DROP SEQUENCE  SEQ_FILME;

DROP TABLE TB_FUNCIONARIO; 
DROP TABLE TB_FILME;



CREATE SEQUENCE  "SYSTEM"."SEQ_FUNCIONARIO"  MINVALUE 1 MAXVALUE 999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "SYSTEM"."SEQ_FILME"  MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;




CREATE TABLE TB_FUNCIONARIO (
matricula INTEGER NOT NULL PRIMARY KEY,
nome VARCHAR(200) NOT NULL,
senha VARCHAR(50) NOT NULL
);



CREATE TABLE TB_FILME (
codigo INTEGER NOT NULL PRIMARY KEY,
titulo VARCHAR(200) NOT NULL,
diretor VARCHAR(120),
genero VARCHAR(50),
preco DECIMAL(9,2) NOT NULL,
qtd_Estoque INT
);