INSERT INTO TB_FUNCIONARIO (MATRICULA, NOME, SENHA) VALUES (SEQ_FUNCIONARIO.nextval, 'João Souza','12345');
INSERT INTO TB_FUNCIONARIO (MATRICULA, NOME, SENHA) VALUES (SEQ_FUNCIONARIO.nextval, 'Maria Carla','12345');
INSERT INTO TB_FUNCIONARIO (MATRICULA, NOME, SENHA) VALUES (SEQ_FUNCIONARIO.nextval, 'José Luiz','12345');


INSERT INTO TB_FILME (CODIGO, TITULO, DIRETOR, GENERO, PRECO, QTD_ESTOQUE) VALUES (SEQ_FILME.nextval,'Filme 1', 'Diretor 1','Ação',23.56,'5');
INSERT INTO TB_FILME (CODIGO, TITULO, DIRETOR, GENERO, PRECO, QTD_ESTOQUE) VALUES (SEQ_FILME.nextval,'Filme 2', 'Diretor 2','Aventura',12.99,'7');
INSERT INTO TB_FILME (CODIGO, TITULO, DIRETOR, GENERO, PRECO, QTD_ESTOQUE) VALUES (SEQ_FILME.nextval,'Filme 3', 'Diretor 3','Romance',15.67,'22');
INSERT INTO TB_FILME (CODIGO, TITULO, DIRETOR, GENERO, PRECO, QTD_ESTOQUE) VALUES (SEQ_FILME.nextval,'Filme 4', 'Diretor 4','Ficção científica',57.32,'34');
INSERT INTO TB_FILME (CODIGO, TITULO, DIRETOR, GENERO, PRECO, QTD_ESTOQUE) VALUES (SEQ_FILME.nextval,'Filme 5', 'Diretor 5','Fantasia',18.64,'3');